# Generated by Django 5.0.2 on 2024-03-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=255)),
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'students',
                'managed': False,
            },
        ),
    ]
